name:                hermeneus
version:             0.1.0.0
github:              "githubuser/hermeneus"
license:             BSD3
author:              "Noriaki Sakamoto"
maintainer:          "mrty.ityt.pt@gmail.com"
copyright:           "2018 Noriaki Sakamoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A sophisticated message internationalization (i18n) library
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/na4zagin3/hermeneus#readme>

dependencies:
- base >= 4.7 && < 5
- yaml >= 0.8 && < 1
- aeson >= 1.2 && < 1.5
- text >= 1.2 && < 2
- bytestring >= 0.10 && < 1
- lens >= 4.13 && < 5
- containers >= 0.5 && < 1
- parsec >= 3.1 && < 4
- parsers
- syb

library:
  source-dirs: src

executables:
  hermeneus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hermeneus

tests:
  hermeneus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hermeneus
    - doctest
    - filepath
    - Glob
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-hspec
    - tasty-quickcheck
    - generic-random
    - quickcheck-unicode
